import React, { useState } from 'react';
import { Mail, X, Loader2, Copy, Check } from 'lucide-react';
import { GoogleGenerativeAI } from '@google/generative-ai';

const genAI = new GoogleGenerativeAI(import.meta.env.VITE_GEMINI_API_KEY);

export default function ExecutiveEmailModal({ project, players, matches, onClose }) {
  const [email, setEmail] = useState('');
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const getPoints = (p) => (p.wins * 3) + (p.draws * 1);

  const handleGenerate = async () => {
    setLoading(true);
    const sorted = [...players].sort((a, b) => getPoints(b) - getPoints(a));
    const top = sorted[0];
    const bottom = sorted[sorted.length - 1];
    const completed = matches.filter(m => m.status === 'COMPLETED').length;
    const scheduled = matches.filter(m => m.status === 'SCHEDULED').length;

    const prompt = `You are a senior VP writing an executive status email. 
Write a formal corporate email (300 words max) summarizing this project:

Project: "${project?.name || 'Q4 Initiative'}"
Format: ${project?.format || 'LEAGUE'}
Active Pods: ${players.length}
Sprints Completed: ${completed}
Sprints Remaining: ${scheduled}
Current Leader: ${top?.team || 'TBD'} (${top?.name || 'N/A'}) with ${top ? getPoints(top) : 0} points and ${top?.goalsFor || 0} yield
Bottom Performer: ${bottom?.team || 'TBD'} (${bottom?.name || 'N/A'}) with ${bottom ? getPoints(bottom) : 0} points

Use heavy corporate jargon. Mention "synergy", "bandwidth", "circle back", "leverage", and "stakeholder alignment". 
Be passive-aggressive about the bottom performer. Praise the top performer excessively.
End with a vaguely threatening call to action about "performance reviews."
Sign off as "The Algorithm" with title "Chief Synergy Optimization Officer."
Format as: Subject line, then the email body.`;

    try {
      const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });
      const result = await model.generateContent(prompt);
      setEmail(result.response.text());
    } catch (err) {
      setEmail(`SUBJECT: URGENT — Q4 Velocity Metrics Require Immediate Attention

Dear Stakeholders,

This is an automated escalation. The AI Oracle was unable to generate your executive digest due to: ${err.message || 'bandwidth constraints'}.

Please circle back with your pod lead to manually compile velocity reports. Failure to comply will be noted in your permanent record.

Regards,
The Algorithm
Chief Synergy Optimization Officer`);
    }
    setLoading(false);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(email);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="font-mono fixed inset-0 z-50 flex items-center justify-center bg-black/90 p-4">
      <div className="bg-white border-4 border-black w-full max-w-3xl max-h-[85vh] flex flex-col shadow-[12px_12px_0px_rgba(0,0,0,1)]">

        <div className="bg-black text-white p-4 flex items-center justify-between border-b-4 border-yellow-400 shrink-0">
          <div className="flex items-center gap-2 font-black uppercase text-lg tracking-tight">
            <Mail size={20} />
            Executive Email Digest
          </div>
          <button onClick={onClose} className="hover:text-yellow-400 transition-colors"><X size={24} /></button>
        </div>

        {!email && !loading ? (
          <div className="p-8 flex flex-col items-center gap-6 text-center">
            <Mail size={48} className="text-black" />
            <div>
              <h3 className="text-xl font-black uppercase tracking-tight mb-2">Generate Executive Digest</h3>
              <p className="text-sm text-gray-600 font-bold max-w-md">
                The AI Oracle will compose a formal status email for distribution to all stakeholders and board members.
              </p>
            </div>
            <button
              onClick={handleGenerate}
              className="bg-black text-white font-black uppercase px-8 py-4 border-2 border-black hover:bg-yellow-400 hover:text-black transition-colors flex items-center gap-2"
            >
              Compose Email
            </button>
          </div>
        ) : loading ? (
          <div className="p-12 flex flex-col items-center gap-4 text-center">
            <Loader2 size={32} className="animate-spin text-black" />
            <p className="text-sm font-bold text-gray-500 animate-pulse">AI Oracle is composing executive correspondence...</p>
          </div>
        ) : (
          <div className="overflow-y-auto p-6 space-y-4">
            <div className="border-l-4 border-yellow-400 bg-gray-50 p-4 mb-4">
              <p className="text-[10px] uppercase tracking-widest font-bold text-gray-400 mb-1">Auto-generated by AI Oracle</p>
              <p className="text-[10px] text-gray-400 font-bold">{new Date().toLocaleString()}</p>
            </div>
            <pre className="whitespace-pre-wrap text-sm leading-relaxed text-gray-800 font-mono">{email}</pre>
            <div className="flex gap-3 mt-4">
              <button
                onClick={handleCopy}
                className="flex-1 bg-black text-white font-black uppercase py-3 border-2 border-black hover:bg-yellow-400 hover:text-black transition-colors flex items-center justify-center gap-2"
              >
                {copied ? <><Check size={16} /> Copied!</> : <><Copy size={16} /> Copy to Clipboard</>}
              </button>
              <button
                onClick={handleGenerate}
                className="flex-1 bg-white text-black font-black uppercase py-3 border-2 border-black hover:bg-gray-100 transition-colors flex items-center justify-center gap-2"
              >
                <Mail size={16} /> Regenerate
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
} 