import React, { useState } from "react";
import { FileText, X, Loader2, Download } from "lucide-react";
import { generateCorporateReview } from "../utils/ai";

export default function QuaterlyReportModal({ players, onClose }) {
    const [reviews, setReviews] = useState({});
    const [loading, setLoading] = useState(false);
    const [generated, setGenerated] = useState(false);

    const handleGenerate = async () => {
        setLoading(true);
        const results = {};

        for (const player of players) {
            try {
                const review = await generateCorporateReview(player);
                results[player.id] = review;
            } catch (err) {
                results[player.id] = "REVIEW GENERATION FAILED: Associate has been flagged for manual evaluation.";
            }
        }
        setReviews(results)
        setGenerated(true)
        setLoading(false)
    } ;

    return (
        <div className="font-mono fixed inset-0 z-50 flex items-center justify-center bg-black/90 p-4">
            <div className="bg-white border-4 border-black w-full max-w-3xl max-h-[85vh] flex flex-col shadow-[12px_12px_0px_rgba(0,0,0,1)]">
                <div className="bg-black text-white p-4 flex items-center justify-between border-b-4 border-yellow-400 shrink-0">
                    <div className="flex items-center gap-2 font-black uppercase text-lg tracking-tight">
                        <FileText size={20} />
                        Quaterly Performance Report
                    </div>
                    <button onClick={onClose} className="hover:text-yellow-400 transition-colors"><X size={24} /></button>
                </div>

                {!generated ? (
                    <div className="p-8 flex flex-col items-center gap-6 text-center">
                        <FileText size={48} className="text-black" />
                        <div>
                            <h3 className="text-xl font-black uppercase tracking-tight mb-2">
                                Generate Quaterly Performance Reviews
                            </h3>
                            <p className="text-sm text-gray-600 font-bold max-w-md">
                                The AI Oracle will evaluate {players.length} Associates and generate mandatory Quaterly assesments.
                            </p>
                        </div>
                        <button
                            onClick={handleGenerate}
                            disabled={loading}
                            className="bg-black text-white font-black uppercase px-8 py-4 border-2 border-black hover:bg-yellow-400 hover:text-black transition-colors flex items-center gap-2"
                        >
                            {loading ? <><Loader2 size={16} className="animate-spin" /> Evaluating Associates...</> : 'Generate All Reviews'}
                        </button>

                        {loading && (
                            <p className="text-xs text-gray-500 font-bold animate-pulse">
                                Processing {players.length} reviews... This might take a while
                            </p>
                        )}
                    </div>
                ) : (
                    <div className="overflow-y-auto space-y-4">
                        <div className="text-center border-b-2 border-black pb-4 mb-4">
                            <p className="text-xs uppercase tracking-widest font-bold text-gray-500">Confidential - Do Not Distribute</p>
                            <h2 className="text-2xl font-black uppercase tracking-tight mt-1">Associate Evaluation Summary</h2>
                            <p className="text-xs font-bold text-gray-400 mt-1">Auto generated by AI Oracle • {new Date().toLocaleDateString()}</p>
                        </div>

                        {players.map((player, i) => (
                            <div key={player.id} className="border-2 border-black p-4">
                                <div className="flex justify-between items-start mb-2">
                                    <div>
                                        <h4 className="font-black uppercase text-lg tracking-tight">{player.name}</h4>
                                        <p className="text-xs font-bold text-gray-500">{player.team} • Yield: {player.goalsFor}G / {player.assists}A</p>
                                    </div>
                                    <span className="text-xs font-black bg-black text-white px-2 py-1">#{i + 1}</span>
                                </div>
                                <p className="text-sm leading-relaxed text-gray-800 font-medium italic">
                                    "{reviews[player.id] || 'Review pending...'}"
                                </p>
                            </div>
                        ))}
                        <button
                            onClick={() => window.print()}
                            className="w-full bg-black text-white font-black uppercase py-4 border-2 border-black hover:bg-yellow-400 hover:text-black transition-colors flex items-center justify-center gap-2 mt-4"
                        >
                            <Download size={16} /> Export for HR Distribution
                        </button>
                    </div>
                )}
            </div>
        </div>
    )
};